project:
  type: book
  output-dir: docs

book:
  title: "Computational Publishing for Archives"
  author: "Simon Worthington"
  date: "09/11/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - hello.qmd
    - computations.ipynb
    - linked_open_data.ipynb
    - orcid_get_works_by_person.ipynb
    - references.qmd
  repo-url: https://github.com/NFDI4Culture/cp4a/
  repo-actions: [edit]
  downloads: [pdf]

comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
